apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
type: Opaque
stringData:
  access-key: "YOUR_AWS_ACCESS_KEY_ID"
  secret-key: "YOUR_AWS_SECRET_ACCESS_KEY"
  role-arn: "arn:aws:iam::<account-id>:role/springboot-s3-app-role"
