apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
type: Opaque
stringData:
  access-key: "REPLACE_WITH_AWS_ACCESS_KEY_ID_OR_LEAVE_EMPTY_FOR_IAM_ROLE"
  secret-key: "REPLACE_WITH_AWS_SECRET_ACCESS_KEY_OR_LEAVE_EMPTY_FOR_IAM_ROLE"
  role-arn: "REPLACE_WITH_IAM_ROLE_ARN_FOR_IRSA_OR_LEAVE_EMPTY"
